### ISSUE TITLE
Duplicate a section 

### ISSUE THREAD

**Issue by bahiirwa** [BaronVonPerko/wpcui#14]
With edits and deletes allowed, is there a possibility of duplicating a section and just editing it as it is in ACF? I was looking for this when a section I made was just a copy paste edit situation for me

**Comment by BaronVonPerko** [comment]
With the latest changes to how the options settings are saved, this should be a pretty simple feature to knock out.

**Comment by BaronVonPerko** [comment]
Completed in the dev branch 🔥
