### ISSUE TITLE
Front End validation for controls

### ISSUE THREAD

**Issue by bahiirwa** [BaronVonPerko/wpcui#17]
The email, Url and number controls by default take the html validation of the fields but htese remain with users shortcomings.

Can a validation of each be added to give notices to user to be clinical in their iNput?

![Screen Shot 2019-08-09 at 17 46 10](https://user-images.githubusercontent.com/7713923/62787562-9f964c00-bacd-11e9-9dac-584ea9ec99ee.png)

**Comment by BaronVonPerko** [comment]
```php
$wp_customize->add_setting(...
```

This code can take a **sanitize_callback** function to sanitize the front-end in the customizer.

**Comment by BaronVonPerko** [comment]
Success! 
![image](https://user-images.githubusercontent.com/5384791/82258687-472b8f00-9928-11ea-9087-d57021a65b58.png)
