### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by jekayode** [BaronVonPerko/wpcui#18]
I couldn't activate the plugin.
Encountered '**Plugin could not be activated because it triggered a fatal error.**" after installation. 

<img width="1103" alt="Screenshot 2019-10-02 at 8 29 32 AM" src="https://user-images.githubusercontent.com/18671013/66025774-2aecf600-e4ef-11e9-89b4-23c4aa34e470.png">

**Comment by jekayode** [comment]
Checking the **index.php** and **wpcui.php**, I noticed _**/vendor/autoload.php**_ was referenced but the folder is not present by default.

To fix, I just `cd` to the plugin folder and run `composer install`

<img width="450" alt="Screenshot 2019-10-02 at 8 36 59 AM" src="https://user-images.githubusercontent.com/18671013/66026036-d39b5580-e4ef-11e9-930c-00b1082adfcc.png">

And the error was gone!

**Comment by BaronVonPerko** [comment]
Yep, the plugin requires composer.  I'll update the readme file 👍
