### ISSUE TITLE
2.0 message regarding new plugin location

### ISSUE THREAD

**Issue by BaronVonPerko** [BaronVonPerko/wpcui#44]
The plugin has been moved under "Tools".  Need to add a message when the plugin is upgraded to 2.0 to alert the user of where to find the plugin now that it is not a standalone admin page.

**Comment by bahiirwa** [comment]
Wouldn't a plugin link suffice? One right next to the activate and deactivate buttons?

**Comment by BaronVonPerko** [comment]
Yeah I like that idea better than something like a banner on the page!
